[Distribution]
Distribution=fedora
Release=43

[Output]
Format=disk
ImageId=xiboplayer-kiosk
OutputDirectory=output

[Content]
Bootable=yes
Bootloader=grub
UnifiedKernelImages=no
RootPassword=root
ExtraTrees=mkosi-extra
Packages=
    @core
    kernel-core
    efibootmgr
    shim-x64
    grub2-efi-x64
    gdm
    gnome-kiosk
    gnome-kiosk-script-session
    qt6-qtwebengine
    dbus
    zeromq
    vlc
    firefox
    avahi
    nss-mdns
    wireguard-tools
    gstreamer1-plugins-base
    gstreamer1-plugins-good
    gstreamer1-plugins-bad-free
    gstreamer1-plugins-ugly-free
    gstreamer1-plugin-openh264
    gstreamer1-plugin-libav
    NetworkManager-wifi
    linux-firmware
    mesa-va-drivers
    libva
    arexibo
    xiboplayer-electron
    xiboplayer-chromium
    xiboplayer-kiosk
    keyd
    python3-gobject
    libadwaita
    gnome-initial-setup
    mesa-dri-drivers
    opendoas
    systemd-cryptsetup
    ffmpeg
    ffmpeg-libs
RemovePackages=
    ffmpeg-free

[Runtime]
Firmware=uefi
