[Distribution]
Distribution=fedora
Release=43

[Output]
Format=disk
ImageId=xiboplayer-kiosk
OutputDirectory=output

[Content]
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=no
KernelCommandLine=root=gpt-auto quiet rhgb
RootPassword=root
ExtraTrees=mkosi-extra
Packages=
    @core
    kernel-core
    efibootmgr
    systemd-boot-unsigned
    gdm
    gnome-kiosk
    gnome-kiosk-script-session
    avahi
    nss-mdns
    wireguard-tools
    NetworkManager-wifi
    linux-firmware
    vlc
    mpv
    dunst
    unclutter
    zenity
    gnome-terminal
    opendoas
    keyd
    mesa-dri-drivers
    mesa-va-drivers
    libva
    gstreamer1-plugins-base
    gstreamer1-plugins-good
    gstreamer1-plugins-bad-free
    gstreamer1-plugins-bad-freeworld
    gstreamer1-plugins-ugly-free
    gstreamer1-plugins-ugly
    gstreamer1-plugin-openh264
    gstreamer1-plugin-libav
    ffmpeg
    ffmpeg-libs
    dejavu-sans-fonts
    dejavu-sans-mono-fonts
    google-noto-sans-fonts
    google-noto-emoji-color-fonts
    xiboplayer-electron
    xiboplayer-chromium
    xiboplayer-kiosk
RemovePackages=
    ffmpeg-free
    gnome-initial-setup

[Runtime]
Firmware=uefi
