permit nopass xibo cmd reboot
permit nopass xibo cmd shutdown
permit nopass xibo cmd alternatives
permit nopass xibo cmd localectl
permit nopass xibo cmd timedatectl
permit nopass xibo cmd systemctl args restart NetworkManager
permit nopass xibo cmd /usr/share/xiboplayer-kiosk/xibo-activate-kiosk.sh
permit nopass xibo cmd /usr/share/xiboplayer-kiosk/xibo-deactivate-kiosk.sh
