name: Build Kiosk Images

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  build:
    uses: xibo-players/.github/.github/workflows/build-iso.yml@5c3b3699cd05c12bb3ec76e5d1d317d539dd69b4  # main
    with:
      package-name: xiboplayer-kiosk
      kickstart-file: 'kickstart/xiboplayer-kiosk.ks'
      build-disk-images: true
      build-self-contained-iso: true
      build-netinstall: true
      architectures: 'x86_64,aarch64'
    secrets: inherit
